### ISSUE TITLE
Catching up with backlog

### ISSUE THREAD

**Issue by Beanow** [sfosc/sfosc#67]
Since I just received maintainer access, my goal is to catch up with some of the backlog starting next week. Here is an issue to keep you informed and track progress.

- [x] Self introduction, posted in #70
- [x] Talk about specifics of my role and how it fits governance here, started in #70 
- [x] Merge non-controversial open PRs.
- [x] Address remaining PRs, either based on consensus or outcome of governance discussion.
- [ ] Start looking at which issues could become PRs, for example #28
- [ ] Access to github pages repository #79

Suggestions and recommendations welcome :]

**Comment by Beanow** [comment]
The majority of PRs have moved along now. There are still issues that are discussed and actionable, I think we should look at that. Most blocking right now though is needing access to update the github pages repository. #79

**Comment by Beanow** [comment]
I think, the #78 open call for input on what's next will be prioritized over suggestions from older issues.
And access problems can be tracked in their respective issues now. This can be closed now I think.
